name: "Go Beautiful HTML Coverage"
description: "A GitHub Action to track code coverage in your pull requests, with a beautiful HTML preview, for free."
author: "Aleksey Safronov"

branding:
  icon: "bar-chart"
  color: "blue"

inputs:
  repository:
    description: "Repository name with owner. For example, IcedElect/oh-my-cover-go"
    default: ${{ github.repository }}
  profilePath:
    description: "Path to the coverage profile file. Default is ./coverage.out"
    default: "./coverage.out"
  branch:
    default: cover
    description: The branch to checkout or create and push coverage to.
  path:
    description: The relative path of your go project. Useful for monorepos and custom folder structures.
    default: "./"
  threshold:
    description: The minimum % of coverage required.
    default: "0"

runs:
  using: composite
  steps:
    - name: Install oh-my-cover-go
      shell: bash
      run: GOBIN=$(pwd)/bin go install github.com/IcedElect/oh-my-cover-go/cmd/oh-my-cover-go@latest

    - name: Process coverage profile
      shell: bash
      run: |
        if [ -f "${{ inputs.profilePath }}" ]; then
          echo "Processing coverage profile at ${{ inputs.profilePath }}"
          ./bin/oh-my-cover-go --profile="${{ inputs.profilePath }}" --output="oh-my-covererage"
        else
          echo "No coverage profile found at ${{ inputs.profilePath }}. Skipping processing."
        fi

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload entire repository
        path: oh-my-covererage

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
