name: "Go Beautiful HTML Coverage"
description: "A GitHub Action to track code coverage in your pull requests, with a beautiful HTML preview, for free."
author: "Aleksey Safronov"

branding:
  icon: "bar-chart"
  color: "blue"

inputs:
  version:
    description: "Version of oh-my-cover-go to use. Default is latest."
    default: "latest"
  repository:
    description: "Repository name with owner. For example, IcedElect/oh-my-cover-go"
    default: ${{ github.repository }}
  profilePath:
    description: "Path to the coverage profile file. Default is ./coverage.out"
    default: "./coverage.out"
  branch:
    default: cover
    description: The branch to checkout or create and push coverage to.
  path:
    description: The relative path of your go project. Useful for monorepos and custom folder structures.
    default: "./"
  threshold:
    description: The minimum % of coverage required.
    default: "0"

runs:
  using: composite
  steps:
    - name: Install oh-my-cover-go
      shell: bash
      run: GOBIN=$(pwd)/bin go install github.com/IcedElect/oh-my-cover-go/cmd/oh-my-cover-go@${{ inputs.version }}

    - name: Process coverage profile
      continue-on-error: true
      shell: bash
      id: coverage
      run: |
        if [ -f "${{ inputs.profilePath }}" ]; then
          echo "Processing coverage profile at ${{ inputs.profilePath }}"
          set +e
          RESULT=$(./bin/oh-my-cover-go -p "${{ inputs.profilePath }}" -o "oh-my-covererage" --threshold="${{ inputs.threshold }}")
          code=$?
          set -e

          if [ $code -ne 0 && $code -ne 10 ]; then
            echo "Error processing coverage profile: $RESULT"
            exit $code
          else
            echo "Coverage profile processed successfully."
          fi

          echo "coveragePercent=${{ env.coverage_percent }}"

          echo "code=$code" >> "$GITHUB_OUTPUT"
          echo "result=$RESULT" >> "$GITHUB_OUTPUT"
        else
          echo "No coverage profile found at ${{ inputs.profilePath }}. Skipping processing."
          echo "code=0" >> "$GITHUB_OUTPUT"
        fi

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload entire repository
        path: "./oh-my-covererage"

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

    - name: Conditional step
      shell: bash
      if: ${{ steps.coverage.outputs.code != '0' }}
      run: |
        echo "::error::${{ steps.coverage.outputs.result }}"
        echo "coverage report url: ${{ steps.deployment.outputs.page_url }}"
        echo "### Test coverage threshold \n ${{ steps.coverage.outputs.threshold }}" >> $GITHUB_STEP_SUMMARY
        exit 1
