# Directory for storing executable binaries 
# of dependencies tools, needed for development and testing.
LOCAL_BIN := ${PWD}/bin

# File name for storing test coverage profile data, generated by `go test` command.
COVER_PROFILE_FILE := coverage.out

.cover-profile: ## Generate .coverprofile file with test coverage data
	${info Generating test coverage profile data in $(COVER_PROFILE_FILE)...}
	go test -coverprofile=$(COVER_PROFILE_FILE) ./...

.run: .cover-profile
	${info Running goverage with test coverage profile data from $(COVER_PROFILE_FILE)...}
	@go run ./... --profile=$(COVER_PROFILE_FILE)

.PHONY: run
run: .run ## Run goverage with test coverage profile data

.build: ## Build the project
	${info Building the project...}
	go build -o ${LOCAL_BIN}/goverage ./cmd/goverage

.PHONY: build
build: .build ## Build the project

# Path to the golangci-lint executable file.
GOLANGCI_BIN := $(LOCAL_BIN)/golangci-lint
GOLANGCI_TAG := 2.11.4

.install-lint: export GOBIN := $(LOCAL_BIN)
.install-lint: ## Install golangci-lint in the current directory with executable files
ifeq ($(wildcard $(GOLANGCI_BIN)),)
	@# If the executable file of the linter was not found in previous steps
	@# - install it locally from the source.
	$(info Installing golangci-lint v$(GOLANGCI_TAG))
	go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v$(GOLANGCI_TAG)
# Set the current path for the linter executable.
GOLANGCI_BIN := $(LOCAL_BIN)/golangci-lint
else
	$(info Golangci-lint is already installed to $(GOLANGCI_BIN))
endif

.install-lint-nilaway: export GOBIN := $(LOCAL_BIN)
.install-lint-nilaway: ## Install nilaway (golangci-plugin) in the current directory with executable files
ifeq ($(wildcard $(GOLANGCI_NILAWAY_BIN)),)
	@# If the executable file of nilaway was not found in previous steps
	@# - install it locally from the source.
	$(info Installing nilaway)
	go install go.uber.org/nilaway/cmd/nilaway@latest
else
	$(info Nilaway is already installed to $(GOLANGCI_NILAWAY_BIN))
endif

install-lint: .install-lint .install-lint-nilaway

.lint: install-lint
	$(info Running lint against changed files...)
	$(GOLANGCI_BIN) run \
		--new-from-rev=origin/master \
		--config=.golangci.yaml \
		--max-issues-per-linter=1000 \
		--max-same-issues=1000 \
		./...

lint: .lint ## Run lint against changed files

.lint-full: install-lint
	$(info Running lint against all project files...)
	$(GOLANGCI_BIN) run \
		--config=.golangci.yml \
		--max-issues-per-linter=1000 \
		--max-same-issues=1000 \
		./...

lint-full: .lint-full

.fmt: install-lint
	$(info Форматируем код с помощью golangci-lint...)
	$(GOLANGCI_BIN) run \
		--fix \
		--new-from-rev=origin/${DEFAULT_GIT_BRANCH} \
		--max-issues-per-linter=1000 \
		--max-same-issues=1000 \
		./...

fmt: .fmt ## Запуск форматирования кода

.fmt-full: install-lint
	$(info Форматируем код с помощью golangci-lint...)
	$(GOLANGCI_BIN) run \
		--fix \
		--max-issues-per-linter=1000 \
		--max-same-issues=1000 \
		./...

fmt-full: .fmt-full ## Запуск форматирования кода по всем файлам проекта