name: ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"

      - name: Set up Pages
        uses: actions/configure-pages@v5

      - name: Coverage Profile
        run: go test -coverprofile=coverage.out ./...

      - name: Coverage Report
        uses: IcedElect/goverage@feature/strategy-stdout
        with:
          version: main
          profilePath: coverage.out
          branch: coverage
          threshold: 15
