name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Run tests
        run: go test ./...

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Set up Pages
        uses: actions/configure-pages@v5

      - name: Coverage Profile
        run: go test -coverprofile=coverage.out ./...

      - name: Coverage Report
        uses: IcedElect/oh-my-cover-go@feature/github-actions
